### ISSUE TITLE
cyrcles filters are very small 

### ISSUE THREAD

**Issue by bertol83** [sirensolutions/enhanced_tilemap#126]
Using 10.4-snapshot 

using polygon and rectangle, they are well visible on the map.
![image](https://user-images.githubusercontent.com/13969336/69790719-e0b88600-11ba-11ea-81e9-267959bc058d.png)

Using cycle instead, the generated filter is very small even if the cycle was big
![image](https://user-images.githubusercontent.com/13969336/69790834-1eb5aa00-11bb-11ea-9532-3a9e5a6f3375.png)

generated filter almost invisible
![image](https://user-images.githubusercontent.com/13969336/69790882-35f49780-11bb-11ea-95cb-f3f9ef47d3e4.png)

**Comment by corrigancd** [comment]
Will handle this issue as part of - https://github.com/sirensolutions/kibi-internal/issues/10803
